//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEmpresaService.CentroWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CentroWS.ICentros")]
    public interface ICentros {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentros/CrearCentro", ReplyAction="http://tempuri.org/ICentros/CrearCentroResponse")]
        SCTServiceWCF.Dominio.Centro CrearCentro(string descripcion, int empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentros/ObtenerCentro", ReplyAction="http://tempuri.org/ICentros/ObtenerCentroResponse")]
        SCTServiceWCF.Dominio.Centro ObtenerCentro(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentros/ListarCentro", ReplyAction="http://tempuri.org/ICentros/ListarCentroResponse")]
        SCTServiceWCF.Dominio.Centro[] ListarCentro();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICentrosChannel : TestEmpresaService.CentroWS.ICentros, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CentrosClient : System.ServiceModel.ClientBase<TestEmpresaService.CentroWS.ICentros>, TestEmpresaService.CentroWS.ICentros {
        
        public CentrosClient() {
        }
        
        public CentrosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CentrosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentrosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentrosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SCTServiceWCF.Dominio.Centro CrearCentro(string descripcion, int empresa) {
            return base.Channel.CrearCentro(descripcion, empresa);
        }
        
        public SCTServiceWCF.Dominio.Centro ObtenerCentro(int codigo) {
            return base.Channel.ObtenerCentro(codigo);
        }
        
        public SCTServiceWCF.Dominio.Centro[] ListarCentro() {
            return base.Channel.ListarCentro();
        }
    }
}
