//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAgencia.proxyCentros {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Centro", Namespace="http://schemas.datacontract.org/2004/07/SCTServiceWCF.Dominio")]
    [System.SerializableAttribute()]
    public partial class Centro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebAgencia.proxyCentros.Empresa EMPRESAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_CENTROField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebAgencia.proxyCentros.Empresa EMPRESA {
            get {
                return this.EMPRESAField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPRESAField, value) != true)) {
                    this.EMPRESAField = value;
                    this.RaisePropertyChanged("EMPRESA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_CENTRO {
            get {
                return this.ID_CENTROField;
            }
            set {
                if ((this.ID_CENTROField.Equals(value) != true)) {
                    this.ID_CENTROField = value;
                    this.RaisePropertyChanged("ID_CENTRO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/SCTServiceWCF.Dominio")]
    [System.SerializableAttribute()]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DIRECCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMPRESAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_EMPRESAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebAgencia.proxyCentros.Empresa LISTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELEFONOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DIRECCION {
            get {
                return this.DIRECCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DIRECCIONField, value) != true)) {
                    this.DIRECCIONField = value;
                    this.RaisePropertyChanged("DIRECCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMPRESA {
            get {
                return this.EMPRESAField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPRESAField, value) != true)) {
                    this.EMPRESAField = value;
                    this.RaisePropertyChanged("EMPRESA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_EMPRESA {
            get {
                return this.ID_EMPRESAField;
            }
            set {
                if ((this.ID_EMPRESAField.Equals(value) != true)) {
                    this.ID_EMPRESAField = value;
                    this.RaisePropertyChanged("ID_EMPRESA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebAgencia.proxyCentros.Empresa LISTA {
            get {
                return this.LISTAField;
            }
            set {
                if ((object.ReferenceEquals(this.LISTAField, value) != true)) {
                    this.LISTAField = value;
                    this.RaisePropertyChanged("LISTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUC {
            get {
                return this.RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.RUCField, value) != true)) {
                    this.RUCField = value;
                    this.RaisePropertyChanged("RUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELEFONO {
            get {
                return this.TELEFONOField;
            }
            set {
                if ((object.ReferenceEquals(this.TELEFONOField, value) != true)) {
                    this.TELEFONOField = value;
                    this.RaisePropertyChanged("TELEFONO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxyCentros.ICentros")]
    public interface ICentros {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentros/CrearCentro", ReplyAction="http://tempuri.org/ICentros/CrearCentroResponse")]
        WebAgencia.proxyCentros.Centro CrearCentro(string descripcion, int empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentros/ObtenerCentro", ReplyAction="http://tempuri.org/ICentros/ObtenerCentroResponse")]
        WebAgencia.proxyCentros.Centro ObtenerCentro(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentros/ListarCentro", ReplyAction="http://tempuri.org/ICentros/ListarCentroResponse")]
        WebAgencia.proxyCentros.Centro[] ListarCentro();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICentrosChannel : WebAgencia.proxyCentros.ICentros, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CentrosClient : System.ServiceModel.ClientBase<WebAgencia.proxyCentros.ICentros>, WebAgencia.proxyCentros.ICentros {
        
        public CentrosClient() {
        }
        
        public CentrosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CentrosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentrosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentrosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebAgencia.proxyCentros.Centro CrearCentro(string descripcion, int empresa) {
            return base.Channel.CrearCentro(descripcion, empresa);
        }
        
        public WebAgencia.proxyCentros.Centro ObtenerCentro(int codigo) {
            return base.Channel.ObtenerCentro(codigo);
        }
        
        public WebAgencia.proxyCentros.Centro[] ListarCentro() {
            return base.Channel.ListarCentro();
        }
    }
}
