//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEmpresaService.EmpresaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmpresaWS.IEmpresas")]
    public interface IEmpresas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresas/CrearEmpresa", ReplyAction="http://tempuri.org/IEmpresas/CrearEmpresaResponse")]
        SCTServiceWCF.Dominio.Empresa CrearEmpresa(string empresa, string ruc, string telefono, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresas/ObtenerEmpresa", ReplyAction="http://tempuri.org/IEmpresas/ObtenerEmpresaResponse")]
        SCTServiceWCF.Dominio.Empresa ObtenerEmpresa(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresas/ModificarEmpresa", ReplyAction="http://tempuri.org/IEmpresas/ModificarEmpresaResponse")]
        SCTServiceWCF.Dominio.Empresa ModificarEmpresa(int codigo, string empresa, string ruc, string telefono, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresas/EliminarEmpresa", ReplyAction="http://tempuri.org/IEmpresas/EliminarEmpresaResponse")]
        void EliminarEmpresa(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresas/ListarEmpresa", ReplyAction="http://tempuri.org/IEmpresas/ListarEmpresaResponse")]
        SCTServiceWCF.Dominio.Empresa[] ListarEmpresa();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpresasChannel : TestEmpresaService.EmpresaWS.IEmpresas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpresasClient : System.ServiceModel.ClientBase<TestEmpresaService.EmpresaWS.IEmpresas>, TestEmpresaService.EmpresaWS.IEmpresas {
        
        public EmpresasClient() {
        }
        
        public EmpresasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpresasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SCTServiceWCF.Dominio.Empresa CrearEmpresa(string empresa, string ruc, string telefono, string direccion) {
            return base.Channel.CrearEmpresa(empresa, ruc, telefono, direccion);
        }
        
        public SCTServiceWCF.Dominio.Empresa ObtenerEmpresa(int codigo) {
            return base.Channel.ObtenerEmpresa(codigo);
        }
        
        public SCTServiceWCF.Dominio.Empresa ModificarEmpresa(int codigo, string empresa, string ruc, string telefono, string direccion) {
            return base.Channel.ModificarEmpresa(codigo, empresa, ruc, telefono, direccion);
        }
        
        public void EliminarEmpresa(int codigo) {
            base.Channel.EliminarEmpresa(codigo);
        }
        
        public SCTServiceWCF.Dominio.Empresa[] ListarEmpresa() {
            return base.Channel.ListarEmpresa();
        }
    }
}
